### PR TITLE
ksmbd-tools: add a crossmnt parameter in smb.conf

### PR DESCRIPTION
**Pull request by namjaejeon**
This patch add a new 'crossmnt' parameter in smb.conf to allow path lookup to cross a mountpoint to the root of a different filesystem. e.g. if there is sda1 directory in ksmbd share and sda1 directory is mounted as external devices(e.g. usb), currently files in sda1 is not visiable from client. User can control path lookup for cross mount points using this parameter.

### CODE REVIEW

**Comment by namjaejeon** [comment]
@atheik Can you review this patch ? Thanks!

**Comment by atheik** [comment]
@namjaejeon Other than the missing `.TP`, it looks all good to me. I tested the crossmnt functionality with the out-of-tree ksmbd (https://github.com/namjaejeon/ksmbd/pull/437/commits/34cf739).

**Comment by namjaejeon** [comment]
@atheik  Thanks for your review! I updated it now.

**Review by atheik — APPROVED** [review]

**Comment by namjaejeon** [comment]
@atheik Thanks! I will add your Acked-by tag.

**Pull request closed without merging**
